name: HTML Validation and Artifact Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install -g html-validator-cli

    - name: Validate HTML
      run: |
        # Replace 'index.html' with the correct path to your HTML file
        npx html-validator-cli "AngiePowl/NewRepo/index.html"

    - name: Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-app
        path: AngiePowl/NewRepo  # Relative path to the directory containing "index.html"
