name: Deploy and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-app
        path: https://github.com/AngiePowl/NewRepo  # Relative path to the directory containing "index.html"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: https://github.com/AngiePowl/NewRepo  # Relative path to the directory containing "index.html"
