name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Up Git Configurations
        run: |
          git config --global user.email "angelin.powl@gmail.com"
          git config --global user.name "AngiePowl"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies (if needed)
        run: npm install

      - name: Download index.html
        run: |
          curl -LO https://raw.githubusercontent.com/AngiePowl/NewRepo/main/index.html

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Check if the HTML lint validation test passed
        run: |
          # Run HTMLHint on index.html
          $htmlLintResult = htmlhint index.html

          if ($htmlLintResult.length -eq 0) {
            # If there are no linting errors, continue with creating the zip archive
            Compress-Archive -Path index.html -DestinationPath myArtifact.zip -Force
          } else {
            echo "HTML lint validation test failed. Skipping artifact creation."
          }

      - name: Debug
        run: |
          Write-Host "Current Working Directory: $PWD"

      - name: List Files in Working Directory
        run: ls -R $GITHUB_WORKSPACE

      - name: Add and Commit Changes
        run: |
          for /f %%i in ('git status --porcelain') do (
          set CHANGES=true
           )

          if "%CHANGES%"=="true" (
          git add .
          git commit -m "Add myArtifact.zip"
          ) else (
          echo "No changes to commit."
          )

      - name: Push Changes
        run: |
          git remote add origin_with_token https://$PAT_TOKEN1@github.com/AngiePowl/NewRepo.git
          git push origin_with_token HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN1 }}
      - name: Push Changes
        run: |
          echo "Repository URL: https://$PAT_TOKEN1@github.com/AngiePowl/NewRepo.git"
          git remote add origin_with_token https://$PAT_TOKEN1@github.com/AngiePowl/NewRepo.git
          git push origin_with_token HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN1 }}
