name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Up Git Configurations
        run: |
          git config --global user.email "angelin.powl@gmail.com"
          git config --global user.name "AngiePowl"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies (if needed)
        run: npm install  # Modify this if you have dependencies

      - name: Download index.html
        run: |
          curl -LO https://raw.githubusercontent.com/AngiePowl/NewRepo/main/index.html

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Create Build Artifact
        run: |
          git add .
          git commit -m "Add myArtifact.zip"
          Compress-Archive -Path index.html -DestinationPath myArtifact.zip -Force

      - name: Add and Commit Changes
        run: |
          if (!(git diff-index --quiet HEAD --)); then
          # Add all changes, including index.html and myArtifact.zip
          git add .
          # Commit all changes
          git commit -m "Add myArtifact.zip"
          else
          echo "No changes to commit."
          fi

      - name: Push Changes
        run: |
          git remote add origin_with_token https://$PAT_TOKEN1@github.com/AngiePowl/NewRepo.git
          git push origin_with_token HEAD:main
        env:
          PAT_TOKEN1: ${{ secrets.PAT_TOKEN1 }}
