name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Up Git Configurations
        run: |
          git config --global user.email "angelin.powl@gmail.com"
          git config --global user.name "AngiePowl"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies 
        run: npm install  

      - name: Download index.html
        run: |
          curl -LO https://raw.githubusercontent.com/AngiePowl/NewRepo/main/index.html

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Create Build Artifact
        run: |
          mkdir myArtifact
          cp index.html myArtifact/
          git add myArtifact
          git commit -m "Add myArtifact.zip"
          Compress-Archive -Path myArtifact -DestinationPath myArtifact.zip -Force

      - name: Push Changes
        run: |
          git remote add origin_with_token https://$PAT_TOKEN1@github.com/AngiePowl/NewRepo.git
          git push origin_with_token HEAD:main
        env:
          PAT_TOKEN1: ${{ secrets.PAT_TOKEN1 }}
