name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Up Git Configurations
        run: |
          git config --global user.email "angelin.powl@gmail.com"
          git config --global user.name "AngiePowl"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies (if needed)
        run: npm install  # Modify this if you have dependencies

      - name: Download index.html
        run: |
          curl -LO https://raw.githubusercontent.com/AngiePowl/NewRepo/main/index.html

      - name: Create Zip Archive
        run: |
          # Zip the index.html file
          Compress-Archive -Path index.html -DestinationPath myArtifact.zip -Force

      - name: Debug
        run: |
          Write-Host "Current Working Directory: $PWD"

      - name: List Files in Working Directory
        run: ls -R $GITHUB_WORKSPACE

      - name: Add and Commit Changes
        run: |
          git add myArtifact.zip
          git commit -m "Add myArtifact.zip"

      - name: Push Changes
        run: |
          git remote add origin_with_token https://$PAT_TOKEN@github.com/AngiePowl/NewRepo.git
          git push origin_with_token HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Run HTML Validation Tests
        run: |
          # Install HTMLHint (you may need to adjust this based on your specific testing tool)
          npm install -g htmlhint

#end
