name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies (if needed)
        run: npm install  # Modify this if you have dependencies

    #  - name: Run Basic Tests
     #   run: |
          # Replace with your test command(s)
          # For example, you might use a tool like HTMLLint
          # html-lint index.html

      - name: Create Zip Archive
        run: |
          # Zip the index.html file
          Compress-Archive -Path index.html -DestinationPath website.zip

     # - name: Publish to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
       # with:
        #  github_token: ${{ github.token }}
         # publish_dir: .  # Change this to the directory where your zip file is
          #publish_branch: gh-pages  # Change to your GitHub Pages branch
